Repository FRONTENDBOOTCAMP-13th/JS-07-7zzang-Arcade, pull requests merged in 2025-05, with the labels that each got.

#2 🎉 init : default project folder
  public/fonts/.gitkeep
  public/images/.gitkeep
  public/sounds/.gitkeep
  src/assets/icons/.gitkeep
  src/assets/images/.gitkeep
  src/pages/7zone-war/.gitkeep
  src/pages/animal-patrol/.gitkeep
  src/pages/bbangul/.gitkeep
  src/pages/the-seventh-space/.gitkeep
  src/utils/.gitkeep
Labels: :building_construction: : infra

#4 🎉 init : setting css reset style
  index.html
  prettier.config.js
  src/common/modern-reset.css
  src/style.css
Labels: :building_construction: : infra

#6 ✨ feature : Initialize game setting, player move #5
  src/assets/images/space-img/background.png
  src/assets/images/space-img/boss.png
  src/assets/images/space-img/enemy-bullet.png
  src/assets/images/space-img/enemy1.png
  src/assets/images/space-img/enemy2.png
  src/assets/images/space-img/enemy3.png
  src/assets/images/space-img/explosion.png
  src/assets/images/space-img/heart.png
  src/assets/images/space-img/player-bullet.png
  src/assets/images/space-img/player.png
  src/pages/the-seventh-space/.gitkeep
  src/pages/the-seventh-space/space.css
  src/pages/the-seventh-space/space.html
  src/pages/the-seventh-space/space.ts
  vite.config.js
Labels: 🚀 enhancement, 🔥 priority : 0

#8 ✨ feature : spawn enemies #7
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#11 🍱 assets : DungGeunMo add font #10
  public/fonts/.gitkeep
  public/fonts/DungGeunMo.woff
  public/fonts/DungGeunMo.woff2
  src/style.css
Labels: 🔥 priority : 0, :whale: chore

#12 ✨ feature : player shoots #9
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#20 ✨ feature : create enemy attack function #19
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#23 ✨ faeture : background scrolling #21
  src/assets/images/space-img/background.png
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, ⚡ priority : 1

#26 Feat/UI/tomatobox UI
  src/assets/images/tomato-img/best-socre.png
  src/assets/images/tomato-img/cancel.png
  src/assets/images/tomato-img/select-tomato 2.png
  src/assets/images/tomato-img/timebar.png
  src/assets/images/tomato-img/tomato-empty.png
  src/assets/images/tomato-img/tomato-gameover.png
  src/assets/images/tomato-img/tomato-home.png
  src/assets/images/tomato-img/tomato-intro.png
  src/assets/images/tomato-img/tomato-next.png
  src/assets/images/tomato-img/tomato-nickname.png
  src/assets/images/tomato-img/tomato-play.png
  src/assets/images/tomato-img/tomato-retry.png
  src/assets/images/tomato-img/tomato-savescore.png
  src/assets/images/tomato-img/tomato-start.png
  src/assets/images/tomato-img/tomato-trophy.png
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-intro.html
  src/pages/tomato-box/tomato-intro.ts
  src/pages/tomato-box/tomato-play.html
  src/pages/tomato-box/tomato-play.ts
  vite.config.js
Labels: 🚀 enhancement, 🎯 good first issue, 🔥 priority : 0

#29 🐛 fix: new round delete bullet #28
  src/pages/the-seventh-space/space.ts
Labels: :bug: bug

#33 ✨ feature: space in-game UI #30 in-game function #32
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#35 ✨ feature: space create boss round #34
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#38 ✨ feature : smash7-hit UI 1차 작업 #18
  src/assets/images/smash-img/smash-bat.png
  src/assets/images/smash-img/smash-click.png
  src/assets/images/smash-img/smash-hole-play.png
  src/assets/images/smash-img/smash-home.png
  src/assets/images/smash-img/smash-mole1.png
  src/assets/images/smash-img/smash-mole2.png
  src/assets/images/smash-img/smash-name.png
  src/assets/images/smash-img/smash-over.png
  src/assets/images/smash-img/smash-play.png
  src/assets/images/smash-img/smash-save-nik.png
  src/assets/images/smash-img/smash-save-one.png
  src/assets/images/smash-img/smash-square-lg.png
  src/assets/images/smash-img/smash-square.png
  src/assets/images/smash-img/smash-start.png
  src/assets/images/smash-img/smash-trophy.png
  src/assets/images/smash-img/smash-twinkle.png
  src/assets/images/smash-img/smash-x.png
  src/assets/images/smash-img/start-trophy-pop.png
  src/pages/7zone-war/.gitkeep
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
  vite.config.js
Labels: 🚀 enhancement, 🔥 priority : 0

#40 ✨ feature: space UI 1차 작업 #36
  src/assets/images/space-img/alien-icon.png
  src/assets/images/space-img/home.png
  src/assets/images/space-img/intro.png
  src/assets/images/space-img/title.png
  src/assets/images/space-img/trophy.png
  src/pages/the-seventh-space/space.css
  src/pages/the-seventh-space/space.html
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#41 Feat/animal patrol UI
  src/assets/icons/home.png
  src/assets/icons/trophy.png
  src/assets/images/animal-img/acorns.png
  src/assets/images/animal-img/animal-patrol-t.png
  src/assets/images/animal-img/banana.png
  src/assets/images/animal-img/best-t.png
  src/assets/images/animal-img/bg-grass1.png
  src/assets/images/animal-img/bg-grass2.png
  src/assets/images/animal-img/bg-grass3.png
  src/assets/images/animal-img/boom1.png
  src/assets/images/animal-img/boom2.png
  src/assets/images/animal-img/can.png
  src/assets/images/animal-img/chick-evo1-front.png
  src/assets/images/animal-img/chick-evo1-left.png
  src/assets/images/animal-img/chick-evo1-right.png
  src/assets/images/animal-img/chick-evo2-left.png
  src/assets/images/animal-img/chick-evo2-right.png
  src/assets/images/animal-img/chick-evo3-left.png
  src/assets/images/animal-img/chick-evo3-right.png
  src/assets/images/animal-img/chick-evo4-left.png
  src/assets/images/animal-img/chick-evo4-right.png
  src/assets/images/animal-img/chick-fallen.png
  src/assets/images/animal-img/chick-idle-front.png
  src/assets/images/animal-img/chick-idle-left.png
  src/assets/images/animal-img/chick-idle-right.png
  src/assets/images/animal-img/cloud.png
  src/assets/images/animal-img/fire.png
  src/assets/images/animal-img/frame.png
  src/assets/images/animal-img/game-over-test.png
  src/assets/images/animal-img/game-t.png
  src/assets/images/animal-img/go-animal-patrol-t.png
  src/assets/images/animal-img/go-t.png
  src/assets/images/animal-img/intro-animal.png
  src/assets/images/animal-img/score-chick1.png
  src/assets/images/animal-img/score-chick2.png
  src/assets/images/animal-img/score-chick3.png
  src/assets/images/animal-img/score-chick4.png
  src/assets/images/animal-img/score-chick5.png
  src/assets/images/animal-img/score-frame.png
  src/assets/images/animal-img/score-t.png
  src/assets/images/animal-img/stars-transparent.png
  src/assets/images/animal-img/start-t.png
  src/pages/animal-patrol/.gitkeep
  src/pages/animal-patrol/animal.css
  src/pages/animal-patrol/animal.html
  src/pages/animal-patrol/animal.ts
  src/style.css
  vite.config.js
Labels: 🚀 enhancement, 🔥 priority : 0

#43 ✨ feature: tomato box drag event #31
  src/assets/images/tomato-img/select-tomato.png
  src/pages/tomato-box/tomato-intro.html
  src/pages/tomato-box/tomato-intro.ts
  src/pages/tomato-box/tomato-play.html
  src/pages/tomato-box/tomato-play.ts
  src/pages/tomato-box/tomatobox.css
Labels: 🚀 enhancement, 🔥 priority : 0

#45 ✨ feature: tomato box best score display #37
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
  src/pages/tomato-box/tomato-intro.html
  src/pages/tomato-box/tomato-intro.ts
  src/pages/tomato-box/tomato-play.html
Labels: 🚀 enhancement, 🔥 priority : 0

#47 Fix/tomatobox/link
  src/assets/icons/favicon.ico
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug

#48 Feat/animal intro ingame script
  src/assets/images/animal-img/chick-evo1-front.png
  src/pages/animal-patrol/animal.css
  src/pages/animal-patrol/animal.html
  src/pages/animal-patrol/animal.ts
Labels: :bug: bug, 🚀 enhancement, 🔥 priority : 0

#49 ✨ Feature: html ts css change #39
  src/assets/images/smash-img/smash-memou.png
  src/assets/images/smash-img/smash-score.png
  src/assets/images/smash-img/start-trophy-pop.png
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#53 Fix: tomato box minor corrections, add audio
  public/images/.gitkeep
  public/images/favicon.ico
  public/sounds/.gitkeep
  public/sounds/tomato-effect.wav
  public/sounds/tomato-gameover.wav
  src/assets/icons/favicon.ico
  src/assets/images/tomato-img/select-tomato.png
  src/assets/images/tomato-img/tomato-gameover.png
  src/assets/images/tomato-img/tomato-intro.png
  src/assets/images/tomato-img/tomato-nickname.png
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
  vite.config.js
Labels: :bug: bug, 🚀 enhancement, ⚡ priority : 1

#58 feat/animal patrol enhance
  public/sounds/animal-bgm.mp3
  public/sounds/animal-gameover.wav
  src/pages/animal-patrol/animal.css
  src/pages/animal-patrol/animal.html
  src/pages/animal-patrol/animal.ts
Labels: :bug: bug, 🚀 enhancement, ⚡ priority : 1

#60 [fix] Delete gameover best score, [feat] Add audio to button
  public/sounds/pointer.wav
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug, 🚀 enhancement, ⚡ priority : 1

#61 🐛 fix: space bug - main bgm, edit localstorage, add gameover rule, toast
  public/sounds/space-attack.mp3
  public/sounds/space-bgm.mp3
  public/sounds/space-boss.mp3
  public/sounds/space-gameover.mp3
  src/pages/the-seventh-space/space.css
  src/pages/the-seventh-space/space.html
  src/pages/the-seventh-space/space.ts
Labels: :bug: bug, 🚀 enhancement

#62 ✨ Feat/smash7 hit update
  public/sounds/smash-bgm.mp3
  public/sounds/smash-the-end.mp3
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
Labels: 🚀 enhancement, ⚡ priority : 1

#67 fix: tomato box image path error
  index.html
  src/main.ts
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug, 🔥 priority : 0

#71 [fix] tomato box TypeError, favicon 404 error / [feature] tomato box nickname focus and modify score storage method
  index.html
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug, 🚀 enhancement, 🔥 priority : 0, ⚡ priority : 1

#72 Fix/samsh7 hit upgrade
  public/sounds/smash-home.mp3
  public/sounds/smash-trophy-bgm.mp3
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
Labels: :bug: bug, 🚀 enhancement, 🔥 priority : 0

#73 🐛 fix: switch to import-style image paths and fix main/in-game BGM conflict
  index.html
  src/pages/animal-patrol/animal.ts
Labels: :bug: bug, 🔧 refactor

#75 Fix/samsh7 hit upgrade
  src/pages/animal-patrol/animal.ts
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
  src/pages/the-seventh-space/space.ts
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug, 🚀 enhancement, ⚡ priority : 1

#80 🐛 fix: space cancel bgm start, input tag autocomplete, music
  src/pages/the-seventh-space/space.html
  src/pages/the-seventh-space/space.ts
Labels: :bug: bug

#84 [fix] modify limit nickname latter and modify cancel button location
  src/pages/animal-patrol/animal.ts
  src/pages/smash7-hit/smash.ts
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug

#86 🐛 fix: main loading, game icon, index-screen scaffold, refresh history
  index.html
  public/images/audio-in.png
  public/images/audio-out.png
  public/images/break.png
  public/images/game-poster.png
  public/images/icon-animal.png
  public/images/icon-readme.png
  public/images/icon-space.png
  public/images/icon-wiki.png
  public/images/index-bg.png
  public/images/maingame-bg.png
  src/main.ts
  src/style.css
Labels: :bug: bug, 🔥 priority : 0

#91 [feat] firestore
  .env.example
  package-lock.json
  package.json
  src/pages/animal-patrol/animal.ts
  src/pages/smash7-hit/smash.ts
  src/pages/the-seventh-space/space.ts
  src/pages/tomato-box/tomato-box.ts
  src/utilits/firebase.ts
  src/utilits/scoreService.ts
Labels: 🚀 enhancement, ⚡ priority : 1

#93 ✨ feature: create easter-egg
  .env.example
  index.html
  public/images/animal-profile.png
  public/images/smash-profile.png
  public/images/space-profile.png
  public/images/tomato-profile.png
  src/main.ts
  src/style.css
Labels: 🚀 enhancement, 🔥 priority : 0

#95 feat: limit same nickname
  src/pages/animal-patrol/animal.ts
  src/pages/smash7-hit/smash.ts
  src/pages/the-seventh-space/space.ts
  src/pages/tomato-box/tomato-box.ts
  src/utilits/scoreService.ts
Labels: 🚀 enhancement, ⚡ priority : 1, 🚑 hotfix

#96 ✨ Feat/improve game smash #82
  src/assets/icons/bgm-icon2.webp
  src/assets/icons/bgm-icon3.webp
  src/assets/images/smash-img/smash-popup.webp
  src/assets/images/tomato-img/tomato-popup.webp
  src/pages/smash7-hit/smash.ts
Labels: 🚀 enhancement, ⚡ priority : 1

#99 ✨ feature: implement/how to play
  src/assets/icons/bgm-icon1.png
  src/assets/images/space-img/how-main.png
  src/assets/images/space-img/how-offblack.png
  src/assets/images/space-img/how-offcolor.png
  src/assets/images/space-img/how-onblack.png
  src/assets/images/space-img/how-oncolor.png
  src/pages/the-seventh-space/space.css
  src/pages/the-seventh-space/space.html
  src/pages/the-seventh-space/space.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#102 docs: readme update
  README.md
Labels: 📖 documentation

#103 🐛 fix: change logic
  index.html
  src/main.ts
  src/pages/the-seventh-space/space.css
  src/pages/the-seventh-space/space.ts
  src/style.css
Labels: :bug: bug, 🔥 priority : 0

#105 feat: tomato popup audio
  src/assets/images/tomato-img/bgm-cd.png
  src/assets/images/tomato-img/bgmoff.png
  src/assets/images/tomato-img/bgmon.png
  src/assets/images/tomato-img/tomato-description.png
  src/pages/bbangul/.gitkeep
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
  src/utils/.gitkeep
Labels: 🚀 enhancement, 🔥 priority : 0

#107 ✨ [feature]smash7-hit add BGM features improve game
  src/assets/images/smash-img/smash-popoff.webp
  src/assets/images/smash-img/smash-popon.webp
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
Labels: 🚀 enhancement, 🔥 priority : 0

#117 fix: description popup location, bgm setting
  src/pages/tomato-box/tomato-box.css
  src/pages/tomato-box/tomato-box.html
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug, 🔥 priority : 0

#118 asset/space/ingamelogic
  index.html
  public/images/game-poster.webp
  src/pages/the-seventh-space/space.ts
Labels: :bug: bug, 🚀 enhancement, 🔥 priority : 0

#121 Fix/name check intro reset
  src/pages/animal-patrol/animal.ts
Labels: :bug: bug, 🚑 hotfix

#124 fix: blinking
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug, ⚡ priority : 1

#126 Feat/smash7 hit buildup
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.ts
Labels: 🚀 enhancement, ⚡ priority : 1

#132 fix to firebase rule, time and audio bug
  src/pages/tomato-box/tomato-box.ts
  src/utilits/firebase.ts
  src/utilits/scoreService.ts
Labels: :bug: bug, 🚀 enhancement

#134 🧪 test: Deployment Testing
  src/assets/images/smash-img/smash-popoff.webp
  src/pages/smash7-hit/smash.css
  src/pages/smash7-hit/smash.html
  src/pages/smash7-hit/smash.ts
  src/pages/tomato-box/tomato-box.ts
  src/utilits/firebase.ts
  src/utilits/scoreService.ts
Labels: 🧪 test

#136 fix: trophy button bug, animate tomato function bug
  src/pages/tomato-box/tomato-box.ts
Labels: :bug: bug

#143 [docs] prepare readme
  README.md
Labels: 📖 documentation, 🚀 enhancement, 💤 priority : 2

#144 📝 docs: readme change
  README.md
Labels: 📖 documentation, 🚀 enhancement, 💤 priority : 2

#147 docs/readme
  README.md
Labels: 📖 documentation, 🚑 hotfix
